Algoritmo a estrela
UnBParadigmas2022-1/2022.1_G3_Funcional_ProjetoPacman pull request #1
Opened 2022-06-27 21:58 UTC by Joao-Moura

👉🅰⭐

2022-06-27 22:01 UTC, thiagohdaqw requested changes

2022-06-27 22:01 UTC, thiagohdaqw commented on ProjetoPacman.cabal
> +        base ^>=4.15.1.0,
Acho melhor ficar com o >= pra evitar problemas de dependencia

2022-06-27 22:18 UTC, Joao-Moura commented on ProjetoPacman.cabal
> +        base ^>=4.15.1.0,
Feito

2022-06-28 18:13 UTC, thiagohdaqw requested changes

2022-06-28 18:13 UTC, thiagohdaqw commented on ProjetoPacman.cabal
> +        Utils, AEstrela, Game, Map,
Remover o Utils. Ta dando erro já que o arquivo nao existe mais. 

Aproveita  e coloca as deps assim
![image](https://user-images.githubusercontent.com/54081877/176253451-017f004e-4bc1-4835-9993-9b9b6fb255cf.png)

2022-06-28 23:21 UTC, Joao-Moura commented
@thiagohdaqw preferi seguir o padrão ==X.* porque ele já pega >= X && < X
https://cabal.readthedocs.io/en/latest/developing-packages.html#modules-imported-from-other-packages

2022-06-28 23:22 UTC, thiagohdaqw approved these changes

2022-06-30 01:04 UTC, merged